language: java

sudo: false
matrix:
  include:
    # Ubuntu Linux (trusty) / Oracle JDK 8 / Headless
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"

addons:
  apt:
    packages:
    - oracle-java8-installer


install: true
script:
  - cd Hotel
  - mvn clean install
  - mvn test
after_success:
  - mvn clean test jacoco:report coveralls:report



